name: aradhana
description: A new Flutter project.
publish_to: 'none'

version: 5.2.29+201

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.3.0
  firebase_auth: ^3.3.4
  firebase_analytics: ^9.0.4
  dio: ^4.0.0
  fluttertoast: ^8.0.7
  shared_preferences: ^2.0.6
  hexcolor: ^2.0.4
  flutter_easyloading: ^3.0.0
  flutter_signin_button: ^2.0.0
  firebase_messaging: ^13.0.3
  country_code_picker: ^2.0.2
  font_awesome_flutter: ^9.2.0
  pin_code_fields: ^7.3.0
  step_progress_indicator: ^1.0.1
  flutter_html: ^2.2.1
  intl: ^0.17.0
  share: ^2.0.4
  cupertino_icons: ^1.0.0
  roundcheckbox: ^2.0.4+1
  flutter_local_notifications: ^9.9.1
  url_launcher: ^6.0.7
  package_info: ^2.0.2
  path_provider: ^2.0.2
  permission_handler: ^10.0.2
  pdf: ^3.0.0
  image_gallery_saver: ^1.6.7
  image_picker: ^0.8.1+1
  toggle_switch: ^2.0.1
  whatsapp_unilink: ^2.0.0
  readmore: ^2.1.0
  getwidget: ^3.0.1
  carousel_slider: ^4.0.0
  flutter_pdfview: ^1.1.0
  flutter_cache_manager: ^3.1.2
  expansion_tile_card: ^2.0.0
  expandable: ^5.0.1
  external_app_launcher: ^3.1.0
  flutter_neumorphic: ^3.1.0
  firebase_phone_auth_handler: ^1.0.6
  flutter_custom_clippers: ^2.0.0
  flutter_spinkit:
  random_string:
  flutter_share:
  rename: ^2.0.1
  dotted_border:
  like_button: ^2.0.5
  lottie: ^2.3.2
  video_player:
  chewie:
  better_player:
  photo_view:
#  flick_video_player: ^0.5.0
  webview_flutter:
  youtube_player_flutter:
  flutter_dotenv: ^5.1.0
  flutter_cashfree_pg_sdk: ^2.0.12+15
  advance_pdf_viewer2: ^2.0.4
  dropdown_search: ^5.0.6



  razorpay_flutter: ^1.3.3
  timer_count_down: ^2.2.2

  flutter_lints: ^2.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0

flutter_icons:
  image_path: "assets/appIcon.jpg"
  image_path_ios: "assets/appIcon.jpg"
  android: true
  ios: true

#  flutter pub run flutter_launcher_icons:main

flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/fixedAssets/


  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Light.ttf
          weight: 300
        - asset: fonts/Bold.ttf
          weight: 900
        - asset: fonts/Regular.ttf
          weight: 500